//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int NhanVienId { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<int> PhongBanId { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
    }
}
